version: '3'
services:

    web:
        image: nginx
        container_name: frops_web
        volumes:
            - ./:/app
            - ./configs/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        env_file:
            - configs/.env
        links:
            - db
        restart: always
        depends_on:
            - php
            - db

    php:
        container_name: frops_php
        image: nanoninja/php-fpm:7.1
        restart: always
        ports:
            - 9000:9000
        volumes:
            - ./configs/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./session:/tmp/session
            - ./public:/app/public

    db:
        image: mysql
        container_name: frops_db
        ports:
            - 3306:3306
        env_file:
            - configs/.env.mysql
        restart: always
